<?php

namespace Modules\Core\Product\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Route;


class ProductServiceProvider extends ServiceProvider
{
    const MODULE = "Product";

    /**
     * Utilizado quando a aplicacao eh iniciada
     */
    public function boot()
    {
        Route::namespace("Modules\Core\\".self::MODULE."\Http\Controllers")
            ->middleware(["web"])
            ->group(__DIR__."/../Routes/web.php");

        $this->loadMigrationsFrom(__DIR__."/../Migrations");
    }

    /**
     * Utilizada quando a aplicacao eh registrada
     */
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
