<?php

namespace Tresle\Mocky\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Route;


class MockyServiceProvider extends ServiceProvider
{
    const MODULE = "Mocky";

    /**
     * Utilizado quando a aplicacao eh iniciada
     */
    public function boot()
    {
        Route::namespace("Tresle\\".self::MODULE."\Http\Controllers")
            ->middleware(["api"])
            ->group(__DIR__."/../Routes/api.php");

        $this->loadMigrationsFrom(__DIR__."/../Migrations");

        /**
         * Para utilizar na view:
         *
         * NOME_MODULO::NOME_ARQUIVO_TRADUCAO.CHAVE_ARRAY
         * {{Product::category.title}}
         *
         */
        $this->loadTranslationsFrom(__DIR__."/../lang", self::MODULE);
    }

    /**
     * Utilizada quando a aplicacao eh registrada
     */
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
